# /aifs4su/mmdata/rawdata/videogen/macvid/video_dataset_85/metadata_caption.json
data_root:
  - /aifs4su/mmdata/rawdata/videogen/macvid/videos
META:
  - /aifs4su/mmdata/rawdata/videogen/macvid/metadata/all/video_dataset_85.json

 